import crypto from "node:crypto";
import { config } from "./config.ts";

/**
 * Generate a cryptographically random state parameter for CSRF protection.
 * Format: <timestamp_hex>.<random_hex>.<hmac_hex>
 *
 * The timestamp allows TTL validation on the callback.
 * The HMAC proves the state was generated by this service.
 */
export function generateState(secret: string): string {
  const timestamp = Math.floor(Date.now() / 1000).toString(16);
  const random = crypto.randomBytes(16).toString("hex");
  const payload = `${timestamp}.${random}`;
  const hmac = crypto.createHmac("sha256", secret).update(payload).digest("hex");
  return `${payload}.${hmac}`;
}

/**
 * Validate a state parameter. Checks:
 * 1. Correct format (three dot-separated parts)
 * 2. HMAC integrity (proves it was generated by us)
 * 3. Timestamp freshness (within configured TTL)
 *
 * Uses crypto.timingSafeEqual to prevent timing attacks.
 */
export function validateState(state: string, secret: string): boolean {
  const parts = state.split(".");
  if (parts.length !== 3) return false;

  const [timestamp, random, hmac] = parts as [string, string, string];
  const payload = `${timestamp}.${random}`;

  const expectedHmac = crypto.createHmac("sha256", secret).update(payload).digest("hex");

  if (hmac.length !== expectedHmac.length) return false;

  try {
    const valid = crypto.timingSafeEqual(
      Buffer.from(hmac, "hex"),
      Buffer.from(expectedHmac, "hex"),
    );
    if (!valid) return false;
  } catch {
    return false;
  }

  const stateTime = parseInt(timestamp, 16);
  const now = Math.floor(Date.now() / 1000);
  return now - stateTime <= config.stateTtlSeconds;
}
